### ISSUE TITLE
[Bug] Template variable failed to work when add column

### ISSUE THREAD

**Issue by imReker** [grafana/grafana-infinity-datasource#181]
Try add a variable with demo data in online demo.
https://grafana-infinity-datasource.herokuapp.com/d/try/try

![image](https://user-images.githubusercontent.com/4949937/138836440-44977012-4adf-4748-99e9-a381e9cc6ef3.png)

**Comment by Donal-Goggin** [comment]
What manual edit is needed here? I can't see it in the linked issue

**Comment by yesoreyeram** [comment]
Manually edit the dashboard json will help.

**Comment by Donal-Goggin** [comment]
Thank you for the reply. I realise it's a dashboard JSON edit but I'm not sure where in the JSON to make the edit. Is it the nulls reported by abferm that are the issue? I tried removing those lines and upon saving it just refreshed with all the nulls returned. Setting them to 0 did nothing either. I'm lost about what the actual workaround is
