### ISSUE TITLE
Grafana-Toolkit Plugin is no longer supported.

### ISSUE THREAD

**Issue by fy0001** [grafana/grafana-infinity-datasource#692]
## **Describe the bug**

When using NodeJS v18 to build this Infinity Plugin locally for development, seeing as though [NodeJS v16 is End-of-Life](https://nodejs.dev/en/about/releases/), I get errors that some dependencies defined are incompatible with the Node module. 
It appears Grafana requires plugins to be installed or migrated using the [new create-plugin tool](https://grafana.com/developers/plugin-tools/migration-guides/migrate-from-toolkit).

**Do you have a workaround or set of yarn instructions to get the plugin to build using Node v18? Or are you planning to upgrade the code from the plugin toolkit to the ‘create-plugin’ method ?**

## **Steps to reproduce**

While using Node v18, run 'yarn' to install frontend dependencies, which will result in below errors
![image](https://github.com/yesoreyeram/grafana-infinity-datasource/assets/127891323/0a5bde94-fcbe-42c8-8b19-72ed8edcddb9)

After manually updating dependency versions to coincide with Node v18, building with yarn dev/yarn watch gives an error:
```
$ grafana-toolkit plugin:dev --watch
error: unknown option '--watch'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Running ‘yarn build’, specifies a No Longer Supported Error:
![image](https://github.com/yesoreyeram/grafana-infinity-datasource/assets/127891323/b3935e44-4849-41e6-b948-d5868fc66d78)

## **Version Details:**

- Grafana version : -main (tried 8.47, 9.4.3, and -latest as well)
- Plugin version : 2.1.0

**Comment by evanlally** [comment]
@yesoreyeram any updates on this issue?  We are seeing the same problem.
