### ISSUE TITLE
[Feature request] Support for %20 encoding in URL parameters instead of +

### ISSUE THREAD

**Issue by pstauchCO** [grafana/grafana-infinity-datasource#727]
## **Describe the bug**

In version 2.3.1 the plugin backend began encoding URL spaces as '+' instead ot the expected '%20'. This breaks existing dashboards and queries with spaces in the URL or query parameters and is the incorrect encoding for spaces in a URL. It should not make the assumption that these parameters are joined by '+' signs. This should be a configurable option when configuring a new infinity data source.

## **Steps to reproduce**

Example query: "https://example.com/path/subpath?from=2020-01&to=option1 option2" can be viewed in the query inspector as being sent to the target API as "https://example.com/path/subpath?from=2020-01&to=option1+option2" instead of "https://example.com/path/subpath?from=2020-01&to=option1%20option2"

**Note:** bugs will be fixed only if enough information provided to reproduce the issue

## **Sample Data**

Other example: https://github.com/grafana/grafana-infinity-datasource/discussions/725

## **Version Details:**

- Grafana version : 10.2
- Plugin version : 2.3.1

**Comment by kerrygibian** [comment]
Hi team - An existing customer of ours (150k ARR) is unable to use the infinity plugin due to this issue, which will prevent them from expanding to their customers.

**Comment by kerrygibian** [comment]
Hi there - I sent that over to them and this was their response:

"We don’t have control on customer SaaS solution server to accept space
encoding in + format. This will be the case for other customers who are
requesting this feature. Plugin should have option to select space encoding
to satisfy both types."
