### ISSUE TITLE
Dashboard variables not picked up to achieve dynamic URL requests. 

### ISSUE THREAD

**Issue by ashoktmw** [grafana/grafana-infinity-datasource#790]
Trying to create a variable with datasource type Elasticsearch and getting few values, Having said that with that values i need to get the output of the URL selected from dropdown variable section. 

Reproduce:

Create panel with URL and pass the variables in the URL, you will see below error
Status: 500. Message: error getting data frame. error getting response from url http://TXUWRME4z/_cluster/health?pretty. no response received. Error: Get "http://TXUWRME4z/_cluster/health?pretty=": dial tcp: lookup TXUWRME4z on 10.105.0.10:53: no such host

## **Sample Data**

![image](https://github.com/grafana/grafana-infinity-datasource/assets/58054382/d1149057-7299-4439-99e2-4358e082f43c)

## **Version Details:**

- Grafana version : latest 
- Plugin version : latest

**Comment by zoltanbedi** [comment]
This is not a problem in the plugin. Please ask questions in the forum or in slack.
