### ISSUE TITLE
[Bug] Floating-Point Precision Loss in JSON Data Source with Infinitely Datasource

### ISSUE THREAD

**Issue by iXingo** [grafana/grafana-infinity-datasource#893]
## **Describe the bug**

When using the Infinitely Datasource in Grafana to create a JSON data source, the returned data includes a decimal value of 0.8. However, while the data can be correctly returned as a decimal using CURL, Grafana displays the data as 0, losing the precision and converting the floating-point number to an integer.

## **Steps to reproduce**

1. Create a JSON data source using Infinitely Datasource in Grafana.
2. Ensure the JSON data includes a decimal value, such as 0.8.
3. Use CURL to request the data and verify that the decimal value is correctly returned.
4. Display the data in Grafana and observe that the decimal value is shown as  0 (after setting decimal to 2, it becomes 0.00) instead of 0.8.
![image](https://github.com/grafana/grafana-infinity-datasource/assets/3634305/97e282a8-8177-408b-a42e-3b3a69d94a3d)

**Note:** bugs will be fixed only if enough information provided to reproduce the issue

## **Sample Data**

Here is a sample JSON data:

```json
{
  "value": 0.8
}
```

### CURL Response
![image](https://github.com/grafana/grafana-infinity-datasource/assets/3634305/3c7a56f7-c541-438a-af2c-55290bef384c)

### Grafana Display
![image](https://github.com/grafana/grafana-infinity-datasource/assets/3634305/7d031e4d-7a4b-4f84-9b3c-20d143d448a5)

## **Version Details:**

- Grafana version: 10.4.3
- Plugin version: 2.5.0

## **Additional context**

This issue seems to be related to how Grafana handles floating-point numbers in JSON data sources. It appears that the precision is lost when displaying the data in Grafana. This issue does not occur when using CURL to fetch the data directly.

**Comment by anndavism** [comment]
Adding a comment that this is something I just ran into as well.  It seems that grafana/infinity (not sure which), limits the precision to a single decimal point, no matter what the actual data resolution is for the data returned by the query.
