### ISSUE TITLE
Infinity Play Dashboard Demo panels returning no data

### ISSUE THREAD

**Issue by mjseaman** [grafana/grafana-infinity-datasource#938]
## **Describe the bug**

The Infinity demo on play.grafana.org returns "no data" for the top three panels. The query resolves when I remove the parameters so maybe something changed in the URL params expected by thingspeak.com.

## **Steps to reproduce**

Visit https://play.grafana.org/d/infinity/b20e4c42-3d17-5d39-81be-361ef2018a05 and look at these panels:
* JSON: Traffic density of eastbound and westbound cars
* CSV: Traffic density of eastbound and westbound cars
* XML: Traffic density of eastbound and westbound cars

**Note:** bugs will be fixed only if enough information provided to reproduce the issue

## **Screenshots**

<img width="1444" alt="Screenshot 2024-07-24 at 11 06 12 AM" src="https://github.com/user-attachments/assets/398c41e8-a9b5-495c-96eb-466f6152a83a">

**Comment by ivanahuckova** [comment]
It seems to be working now, so closing the issue :) 

![Image](https://github.com/user-attachments/assets/5f335dab-d11a-4323-8645-a80833e9d0dc)
