### ISSUE TITLE
Instrumentation improvements

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana-infinity-datasource#959]
- [ ] Review all `level=error` and downgrade non-errors. For example `url is not in the allowed list. make sure to match the base URL with the settings`. Errors should signalize that something went unexpectedly bad. If it is "okay" situation that we are handling, it should prbably be debug or warning. 
- [ ] [Change error to downstream](https://ops.grafana-ops.net/goto/757TdtjSR?orgId=1): `error while performing the infinity query. error converting json data to frame: error evaluating JSONata expression\nno results found`
- [ ] Using special characters as “username”/“password” in the URL will lead to those [panics](https://ops.grafana-ops.net/goto/HF-6EFCIR?orgId=1) as `url.Parse`. Maybe implementing something like https://stackoverflow.com/questions/34133617/how-to-parse-an-url-which-contains-special-symbols-using-urlencodedutils-parse? or https://stackoverflow.com/questions/48671938/go-url-parsestring-fails-with-certain-user-names-or-passwords
- [ ] [Change to downstream](https://ops.grafana-ops.net/goto/Ih-hOtCIR?orgId=1) `error="[plugin.downstreamError] client: failed to query data: Failed to query data: rpc error: code = DeadlineExceeded desc = context deadline exceeded" statusSource=plugin`
- [ ] Investigate `error getting data frame. summarize by field not found. Not applying summarize` [here](https://ops.grafana-ops.net/explore?schemaVersion=1&panes=%7B%226q3%22:%7B%22datasource%22:%22000000193%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bslug%3D%5C%22erikpalmans%5C%22%7D%20%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22000000193%22%7D,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22from%22:%221723773913325%22,%22to%22:%221723776417672%22%7D%7D,%22t9g%22:%7B%22datasource%22:%22Em2icyuMk%22,%22queries%22:%5B%7B%22query%22:%2268671dc259313d9b4e3510b784f97767%22,%22queryType%22:%22traceql%22,%22refId%22:%22A%22,%22limit%22:20,%22tableType%22:%22traces%22%7D%5D,%22range%22:%7B%22from%22:%221723811051001%22,%22to%22:%221723812851001%22%7D%7D%7D&orgId=1)

**Comment by Multimo** [comment]
```logger=plugin.instrumentation endpoint=queryData pluginId=yesoreyeram-infinity-datasource dsName="A365 API" dsUID=c6b07d96-97ee-44c7-aa93-ac1009047b8e traceID=d0ed18e528719968ec6371fa7d953438 t=2024-08-16T02:43:27.835302278Z level=error msg="Partial data response error" refID=A status=500 error="error getting data frame. summarize by field not found. Not applying summarize" statusSource=plugin```

**Comment by ivanahuckova** [comment]
Closed in favor of https://github.com/grafana/data-sources/issues/58
